title:        Sanvi Lu
tagline:      "Hyde, a Jekyll theme"
url:          http://sanvibyfish.github.io
author:
  name:       "Sanvi Lu"
  email:      "sanvibyfish@gmail.com"
  avatar:     "https://1.gravatar.com/avatar/ea7613ac0b30a805f357b42bd2e1923c?s=440"
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
